require:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - .bundle/**/*
    - vendor/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Temporarily disable this spec as a it's broken:
# https://github.com/rubocop-hq/rubocop/issues/6254
Layout/RescueEnsureAlignment:
  Enabled: false

Metrics:
  CountComments: false

Metrics/BlockLength:
  AllowedMethods:
    - configure
    - describe
    - context
    - shared_examples

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec:
  Enabled: true
  Include:
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  CountAsOne: [array, hash, heredoc]
  Max: 10

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/CollectionMethods:
  Enabled: true

# [a, b].include?(x) is more unclear than a == x || b == x
Style/MultipleComparison:
  Enabled: false

Style/SafeNavigation:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/CommentedKeyword:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

RSpec/MultipleMemoizedHelpers:
  Enabled: false
